version: '3.5'
services:
  grafana:
    image: lorenzodagostino/ui-cities:v0.0.3
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - API_URL=http://app:5000
  mongo:
    image: mongo:7.0.9
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  app:
    image: lorenzodagostino/cityservice:v0.0.3
    container_name: app
    environment:
      - PORT=5000
      - PUPPETEER_CITY_SCRAPER_ENDPOINT=https://geoportale.cartografia.agenziaentrate.gov.it/age-inspire/srv/ita/catalog.search#/home?pg=
      - PUPPETEER_SLOW_MO_MS=50
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - grafana
volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
