version: '3.5'

services:
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards/cities.json:/var/lib/grafana/dashboards/cities.json
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource,https://github.com/VolkovLabs/volkovlabs-env-datasource/releases/download/v3.1.0/volkovlabs-env-datasource-3.1.0.zip;volkovlabs-env-datasource
      - API_URL=http://app:5000
      # - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/cities.json

  mongo:
    image: mongo:7.0.9
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: app
    command: yarn start:dev
    environment:
    - PORT=5000
    - PUPPETEER_CITY_SCRAPER_ENDPOINT=https://geoportale.cartografia.agenziaentrate.gov.it/age-inspire/srv/ita/catalog.search#/home?pg=
    - PUPPETEER_SLOW_MO_MS=50
    - MONGO_HOST=mongo
    - MONGO_PORT=27017
    - MONGO_USERNAME=root
    - MONGO_PASSWORD=example
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - grafana

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG