import { City } from 'src/cities/entities/city.entity';

export const citiesStub = (): City[] => [
  {
    name: 'MOTTA MONTECORVINO',
    code: 'F777',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'ORDONA',
    code: 'M266',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'MONTELEONE DI PUGLIA',
    code: 'F538',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'ORSARA DI PUGLIA',
    code: 'G125',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'ORTA NOVA',
    code: 'G131',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'PANNI',
    code: 'G312',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'PESCHICI',
    code: 'G487',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'PIETRAMONTECORVINO',
    code: 'G604',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'POGGIO IMPERIALE',
    code: 'G761',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'RIGNANO GARGANICO',
    code: 'H287',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: "ROCCHETTA SANT'ANTONIO",
    code: 'H467',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'RODI GARGANICO',
    code: 'H480',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'ROSETO VALFORTORE',
    code: 'H568',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN FERDINANDO DI PUGLIA',
    code: 'H839',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN GIOVANNI ROTONDO',
    code: 'H926',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN MARCO IN LAMIS',
    code: 'H985',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN MARCO LA CATOLA',
    code: 'H986',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN NICANDRO GARGANICO',
    code: 'I054',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN PAOLO DI CIVITATE',
    code: 'I072',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SAN SEVERO',
    code: 'I158',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: "SANT'AGATA DI PUGLIA",
    code: 'I193',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'SERRACAPRIOLA',
    code: 'I641',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'STORNARA',
    code: 'I962',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'STORNARELLA',
    code: 'I963',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'TORREMAGGIORE',
    code: 'L273',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'TRINITAPOLI',
    code: 'B915',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'TROIA',
    code: 'L447',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'VICO DEL GARGANO',
    code: 'L842',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'VIESTE',
    code: 'L858',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'VOLTURARA APPULA',
    code: 'M131',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'VOLTURINO',
    code: 'M132',
    section: null,
    province: 'FOGGIA',
    provinceCode: 'FG',
    region: 'PUGLIA',
  },
  {
    name: 'ACQUARICA DEL CAPO',
    code: 'A042',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ALLISTE',
    code: 'A208',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ANDRANO',
    code: 'A281',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ALESSANO',
    code: 'A184',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ALEZIO',
    code: 'A185',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ARADEO',
    code: 'A350',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ARNESANO',
    code: 'A425',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'BAGNOLO DEL SALENTO',
    code: 'A572',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'BOTRUGNO',
    code: 'B086',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CALIMERA',
    code: 'B413',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CAMPI SALENTINA',
    code: 'B506',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CAPRARICA DI LECCE',
    code: 'B690',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CARMIANO',
    code: 'B792',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CARPIGNANO SALENTINO',
    code: 'B822',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CASARANO',
    code: 'B936',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CANNOLE',
    code: 'B616',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CASTRI DI LECCE',
    code: 'C334',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: "CASTRIGNANO DE' GRECI",
    code: 'C335',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CASTRIGNANO DEL CAPO',
    code: 'C336',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CASTRO',
    code: 'M261',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CAVALLINO',
    code: 'C377',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CAVALLINO',
    code: 'C377-A',
    section: 'sez.A',
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'COLLEPASSO',
    code: 'C865',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'COPERTINO',
    code: 'C978',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: "CORIGLIANO D'OTRANTO",
    code: 'D006',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CORSANO',
    code: 'D044',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CURSI',
    code: 'D223',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'CUTROFIANO',
    code: 'D237',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'DISO',
    code: 'D305',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GAGLIANO DEL CAPO',
    code: 'D851',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GALATINA',
    code: 'D862',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GALATINA',
    code: 'D862-A',
    section: 'sez.A',
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GALATONE',
    code: 'D863',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GALLIPOLI',
    code: 'D883',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GIUGGIANELLO',
    code: 'E053',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GIURDIGNANO',
    code: 'E061',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'GUAGNANO',
    code: 'E227',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LECCE',
    code: 'E506',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LECCE',
    code: 'E506-A',
    section: 'sez.A',
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LECCE',
    code: 'E506-B',
    section: 'sez.B',
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LEQUILE',
    code: 'E538',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LEVERANO',
    code: 'E563',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LIZZANELLO',
    code: 'E629',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'LIZZANELLO',
    code: 'E629-A',
    section: 'sez.A',
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MAGLIE',
    code: 'E815',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MARTANO',
    code: 'E979',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MARTIGNANO',
    code: 'E984',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MATINO',
    code: 'F054',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MELENDUGNO',
    code: 'F101',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MELISSANO',
    code: 'F109',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MELPIGNANO',
    code: 'F117',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MIGGIANO',
    code: 'F194',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MINERVINO DI LECCE',
    code: 'F221',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MONTERONI DI LECCE',
    code: 'F604',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MONTESANO SALENTINO',
    code: 'F623',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MORCIANO DI LEUCA',
    code: 'F716',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'MURO LECCESE',
    code: 'F816',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: "NARDO'",
    code: 'F842',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'NEVIANO',
    code: 'F881',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'NOCIGLIA',
    code: 'F916',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'NOVOLI',
    code: 'F970',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'ORTELLE',
    code: 'G136',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'OTRANTO',
    code: 'G188',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'PALMARIGGI',
    code: 'G285',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'PARABITA',
    code: 'G325',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: "PATU'",
    code: 'G378',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'POGGIARDO',
    code: 'G751',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'PORTO CESAREO',
    code: 'M263',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
  {
    name: 'PRESICCE',
    code: 'H047',
    section: null,
    province: 'LECCE',
    provinceCode: 'LE',
    region: 'PUGLIA',
  },
];
