name: build-push-main
on:  
  workflow_run:
    workflows: ['ci']
    types: [completed]
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: llorenzinho/city-service/.github/actions/build-push@main
        with:
          ref_name: latest
        secrets: inherit