name: build-push
on:  
  workflow_run:
    workflows: ['ci']
    types: [completed]
    branches:
    - 'main'
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push BE
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cityservice:${{ github.ref_name }}
      
      - name: Build and push FE
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ui
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui-cities:${{ github.ref_name }}