name: build-push
on:  
  name: Callable Workflow

  workflow_call:
    inputs:
      ref_name: 
        description: 'Name for docker tag'
        required: true
        type: 'string'

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push BE
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cityservice:${{ inputs.ref_name }}
      
      - name: Build and push FE
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ui
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui-cities:${{ inputs.ref_name }}