name: build-push-main
on:  
  workflow_run:
    workflows: ['ci']
    types: [completed]
    branches:
    - 'main'

jobs:
  deploy:
    uses: ./.github/workflows/build-push-images.yaml
    with:
      ref_name: latest
    secrets: inherit