name: Create Tag Release
on:
  push:
    tags:        
      - '*'

jobs:
  enhance-tag:
    name: Create tag
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.43.1
        yq-url: https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_{arch}
    - name:
      run: |
        yq e -i '.services.grafana.image = "lorenzodagostino/ui-cities:${{ github.ref_name }}"' compose-app.yaml
        yq e -i '.services.app.image = "lorenzodagostino/cityservice:${{ github.ref_name }}"' compose-app.yaml
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global user.name "Github Actions"
        git checkout -b release/${{ github.ref_name }}
        git add .
        git commit -m "Update compose-app.yaml"
        git push -u origin release/${{ github.ref_name }}
  
  build-tag:
    needs:
    - enhance-tag
    uses: ./.github/workflows/build-push-images.yaml
    with:
      ref_name: ${{ github.ref_name }}
    secrets: inherit

    

