name: Create Tag Release
on:
  push:
    tags:        
      - '*'

jobs:
  build-tag:
    name: Create tag
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.43.1
        yq-url: https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_{arch}
    - name:
      run: |
        yq e -i '.services.grafana.image = "lorenzodagostino/ui-cities:${{ github.ref_name }}"' compose-app.yaml
        yq e -i '.services.app.image = "lorenzodagostino/cityservice:${{ github.ref_name }}"' compose-app.yaml
        git add .
        git commit -m "Update compose-app.yaml"
        git push origin ${{ github.ref_name }}
    - uses: llorenzinho/city-service/.github/workflows/build-push-images.yaml
      with:
        ref_name: ${{ github.ref_name }}
      secrets: inherit

    

