name: Create Tag Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  print-tag:
    name: Print Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print Tag
      run: echo "Creating tag ${{ github.event.inputs.tag }}"

  create-tag:
    name: Create tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.43.1
        yq-url: https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_{arch}
    - name:
      run: |
        yq e -i '.services.grafana.image = "lorenzodagostino/ui-cities:${{ github.event.inputs.tag }}"' compose-app.yaml
        yq e -i '.services.app.image = "lorenzodagostino/cityservice:${{ github.event.inputs.tag }}"' compose-app.yaml
    - name: Commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add . && git commit -m "Update compose-app.yaml"
    - name: Create tag
      run: |
        git tag ${{ github.event.inputs.tag }}
        git push origin ${{ github.event.inputs.tag }}